#ifndef FLUT_MAP_H
#define FLUT_MAP_H

#define FLUT_DO_PP(x) x
#define FLUT_STRINGIFY(x) #x

#define FLUT_MAP_1(mapfn, x)        mapfn(x)
#define FLUT_MAP_2(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_1(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_2(mapfn, __VA_ARGS__))
#define FLUT_MAP_4(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_3(mapfn,  __VA_ARGS__))
#define FLUT_MAP_5(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_4(mapfn,  __VA_ARGS__))
#define FLUT_MAP_6(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_5(mapfn,  __VA_ARGS__))
#define FLUT_MAP_7(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_8(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_7(mapfn,  __VA_ARGS__))
#define FLUT_MAP_9(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_8(mapfn,  __VA_ARGS__))
#define FLUT_MAP_10(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_9(mapfn,  __VA_ARGS__))
#define FLUT_MAP_11(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_10(mapfn,  __VA_ARGS__))
#define FLUT_MAP_12(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_11(mapfn,  __VA_ARGS__))
#define FLUT_MAP_13(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_12(mapfn, __VA_ARGS__))
#define FLUT_MAP_14(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_13(mapfn,  __VA_ARGS__))
#define FLUT_MAP_15(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_14(mapfn,  __VA_ARGS__))
#define FLUT_MAP_16(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_15(mapfn,  __VA_ARGS__))
#define FLUT_MAP_17(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_16(mapfn,  __VA_ARGS__))
#define FLUT_MAP_18(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_17(mapfn,  __VA_ARGS__))
#define FLUT_MAP_19(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_20(mapfn, x, ...)   mapfn(x); FLUT_DO_PP(FLUT_MAP_19(mapfn,  __VA_ARGS__))

#define FLUT_MAP_COMMA_1(mapfn, x)        mapfn(x)
#define FLUT_MAP_COMMA_2(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_1(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_3(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_2(mapfn, __VA_ARGS__))
#define FLUT_MAP_COMMA_4(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_3(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_5(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_4(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_6(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_5(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_7(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_8(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_7(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_9(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_8(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_10(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_9(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_11(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_10(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_12(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_11(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_13(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_12(mapfn, __VA_ARGS__))
#define FLUT_MAP_COMMA_14(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_13(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_15(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_14(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_16(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_15(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_17(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_16(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_18(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_17(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_19(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_COMMA_20(mapfn, x, ...)   mapfn(x), FLUT_DO_PP(FLUT_MAP_COMMA_19(mapfn,  __VA_ARGS__))

#define FLUT_MAP_NO_SEMICOLON_1(mapfn, x)        mapfn(x)
#define FLUT_MAP_NO_SEMICOLON_2(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_1(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_3(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_2(mapfn, __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_4(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_3(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_5(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_4(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_6(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_5(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_7(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_8(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_7(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_9(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_8(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_10(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_9(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_11(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_10(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_12(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_11(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_13(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_12(mapfn, __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_14(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_13(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_15(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_14(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_16(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_15(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_17(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_16(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_18(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_17(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_19(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON_20(mapfn, x, ...)   mapfn(x) FLUT_DO_PP(FLUT_MAP_NO_SEMICOLON_19(mapfn,  __VA_ARGS__))

#define FLUT_MAP_2_AT_TIME_2(mapfn, x, y)       mapfn(x, y)
#define FLUT_MAP_2_AT_TIME_4(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_2(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_6(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_4(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_8(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_10(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_8(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_12(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_10(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_14(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_12(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_16(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_14(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_18(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_16(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_20(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_22(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_20(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_24(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_22(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_26(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_24(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_28(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_26(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_30(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_28(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_32(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_30(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_34(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_32(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_36(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_34(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_38(mapfn, x, y, ...)   mapfn(x, y), FLUT_DO_PP(FLUT_MAP_2_AT_TIME_36(mapfn,  __VA_ARGS__))

#define FLUT_MAP_2_AT_TIME_WITH_SPACE_2(mapfn, x, y)       mapfn(x, y)
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_4(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_2(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_6(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_4(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_8(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_10(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_8(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_12(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_10(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_14(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_12(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_16(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_14(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_18(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_16(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_20(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_22(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_20(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_24(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_22(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_26(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_24(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_28(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_26(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_30(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_28(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_32(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_30(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_34(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_32(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_36(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_34(mapfn,  __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE_38(mapfn, x, y, ...)   mapfn(x, y) FLUT_DO_PP(FLUT_MAP_2_AT_TIME_WITH_SPACE_36(mapfn,  __VA_ARGS__))

#define FLUT_MAP_3_AT_TIME_3(mapfn, x, y, z)       mapfn(x, y, z)
#define FLUT_MAP_3_AT_TIME_6(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_3(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_9(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_12(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_9(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_15(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_12(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_18(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_15(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_21(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_24(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_21(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_27(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_24(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_30(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_27(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_33(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_30(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_36(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_33(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_39(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_36(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_42(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_39(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_45(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_42(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_48(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_45(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_51(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_48(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_54(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_51(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_57(mapfn, x, y, z, ...)   mapfn(x, y, z), FLUT_DO_PP(FLUT_MAP_3_AT_TIME_54(mapfn,  __VA_ARGS__))

#define FLUT_MAP_3_AT_TIME_WITH_SPACE_3(mapfn, x, y, z)       mapfn(x, y, z)
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_6(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_3(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_9(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_6(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_12(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_9(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_15(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_12(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_18(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_15(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_21(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_18(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_24(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_21(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_27(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_24(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_30(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_27(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_33(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_30(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_36(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_33(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_39(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_36(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_42(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_39(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_45(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_42(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_48(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_45(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_51(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_48(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_54(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_51(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_57(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_54(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_60(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_57(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_63(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_60(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_66(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_63(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_69(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_66(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_72(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_69(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_75(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_72(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_78(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_75(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_81(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_78(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_84(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_81(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_87(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_84(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_90(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_87(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_93(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_90(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_96(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_93(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_99(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_96(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_102(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_99(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_105(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_102(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_108(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_105(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_111(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_108(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_114(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_111(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_117(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_114(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_120(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_117(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_123(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_120(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_126(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_123(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_129(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_126(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_132(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_129(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_135(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_132(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_138(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_135(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_141(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_138(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_144(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_141(mapfn,  __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE_147(mapfn, x, y, z, ...)   mapfn(x, y, z) FLUT_DO_PP(FLUT_MAP_3_AT_TIME_WITH_SPACE_144(mapfn,  __VA_ARGS__))

#define FLUT_MAP_ARG_1(mapfn, arg, x)       mapfn(arg, x)
#define FLUT_MAP_ARG_2(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_1(mapfn, arg, __VA_ARGS__))
#define FLUT_MAP_ARG_3(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_2(mapfn, arg, __VA_ARGS__))
#define FLUT_MAP_ARG_4(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_3(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_5(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_4(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_6(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_5(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_7(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_6(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_8(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_7(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_9(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_8(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_10(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_9(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_11(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_10(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_12(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_11(mapfn, arg, __VA_ARGS__))
#define FLUT_MAP_ARG_13(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_12(mapfn, arg, __VA_ARGS__))
#define FLUT_MAP_ARG_14(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_13(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_15(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_14(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_16(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_15(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_17(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_16(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_18(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_17(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_19(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_18(mapfn, arg,  __VA_ARGS__))
#define FLUT_MAP_ARG_20(mapfn, arg, x, ...)  mapfn(arg, x); FLUT_DO_PP(FLUT_MAP_ARG_19(mapfn, arg,  __VA_ARGS__))

#define FLUT_MAP_FILTER_1(mapfn, filter, arg, x)        FLUT_MAP(mapfn, filter(arg, x))
#define FLUT_MAP_FILTER_2(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_1(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_3(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_2(mapfn, filter, arg, __VA_ARGS__))
#define FLUT_MAP_FILTER_4(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_3(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_5(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_4(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_6(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_5(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_7(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_6(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_8(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_7(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_9(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_8(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_10(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_9(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_11(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_10(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_12(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_11(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_13(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_12(mapfn, filter, arg, __VA_ARGS__))
#define FLUT_MAP_FILTER_14(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_13(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_15(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_14(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_16(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_15(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_17(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_16(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_18(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_17(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_19(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_18(mapfn, filter, arg,  __VA_ARGS__))
#define FLUT_MAP_FILTER_20(mapfn, filter, arg, x, ...)   FLUT_MAP(mapfn, filter(arg, x)); FLUT_DO_PP(FLUT_MAP_FILTER_19(mapfn, filter, arg,  __VA_ARGS__))

#define FLUT_COUNT_ARGS(...) FLUT_COUNT_ARGS_(__VA_ARGS__, FLUT_COUNT_TO_N())
#define FLUT_COUNT_ARGS_(...) FLUT_DO_PP(FLUT_GET_PARAM_AT_N(__VA_ARGS__))
#define FLUT_GET_PARAM_AT_N(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30,                \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60,                               \
    _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, _90,                               \
    _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120,          \
    _121, _122, _123, _124, _125, N, ...) N

#define FLUT_COUNT_TO_N() 125, 124, 123, 122, 121, 120,                                                                                                 \
    119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90,         \
    89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,                             \
    59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,                             \
    29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0

#define FLUT_CONCAT(x,y) x##y

#define FLUT_MAP_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP(mapfn, ...) FLUT_MAP_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_COMMA_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_COMMA_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_COMMA(mapfn, ...) FLUT_MAP_COMMA_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_NO_SEMICOLON_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_NO_SEMICOLON_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_NO_SEMICOLON(mapfn, ...) FLUT_MAP_NO_SEMICOLON_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_2_AT_TIME_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_2_AT_TIME_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME(mapfn, ...) FLUT_MAP_2_AT_TIME_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_2_AT_TIME_WITH_SPACE_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_2_AT_TIME_WITH_SPACE_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_2_AT_TIME_WITH_SPACE(mapfn, ...) FLUT_MAP_2_AT_TIME_WITH_SPACE_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_3_AT_TIME_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_3_AT_TIME_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME(mapfn, ...) FLUT_MAP_3_AT_TIME_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_3_AT_TIME_WITH_SPACE_(N, mapfn, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_3_AT_TIME_WITH_SPACE_, N)(mapfn, __VA_ARGS__))
#define FLUT_MAP_3_AT_TIME_WITH_SPACE(mapfn, ...) FLUT_MAP_3_AT_TIME_WITH_SPACE_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, __VA_ARGS__)

#define FLUT_MAP_ARG_(N, mapfn, arg, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_ARG_, N)(mapfn, arg, __VA_ARGS__))
#define FLUT_MAP_ARG(mapfn, arg, ...) FLUT_MAP_ARG_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, arg, __VA_ARGS__)

#define FLUT_MAP_FILTER_(N, mapfn, filter, arg, ...) FLUT_DO_PP(FLUT_CONCAT(FLUT_MAP_FILTER_, N)(mapfn, filter, arg, __VA_ARGS__))
#define FLUT_MAP_FILTER(mapfn, filter, arg, ...) FLUT_MAP_FILTER_(FLUT_COUNT_ARGS(__VA_ARGS__), mapfn, filter, arg, __VA_ARGS__)

#endif /* FLUT_MAP_H */
