mkdir obj\\x86_64 
if not exist .\include (mkdir .\include)
if not exist .\include\fllib (mkdir .\include\fllib)
if not exist .\include\flut (mkdir .\include\flut)
xcopy /y /d /s .\src\*.h .\include\fllib
xcopy /y /d /s .\flut\src\*.h .\include\flut
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\BinaryHeap.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\BinaryHeap.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Container.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Container.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Hashtable.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Hashtable.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Iterator.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Iterator.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\List.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\List.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Vector.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Vector.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Process.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Process.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Signal.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Signal.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\System.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\System.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Timer.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Timer.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\Regex.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\Regex.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\String.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\String.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\Unicode.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\Unicode.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\UnicodeData.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\UnicodeData.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\threading\Thread.c -o obj\win-cmd\x86_64\clang\clang-debug\src\threading\Thread.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Array.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Array.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Cstring.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Cstring.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Error.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Error.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\IO.c -o obj\win-cmd\x86_64\clang\clang-debug\src\IO.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Mem.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Mem.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Slice.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Slice.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Std.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Std.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c src\os\WinEx.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\WinEx.o 
llvm-lib.exe /NOLOGO /OUT:build\win-cmd\x86_64\clang\clang-debug\libfl.lib  obj\win-cmd\x86_64\clang\clang-debug\src\containers\BinaryHeap.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Container.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Hashtable.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Iterator.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\List.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Vector.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Process.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Signal.o obj\win-cmd\x86_64\clang\clang-debug\src\os\System.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Timer.o obj\win-cmd\x86_64\clang\clang-debug\src\text\Regex.o obj\win-cmd\x86_64\clang\clang-debug\src\text\String.o obj\win-cmd\x86_64\clang\clang-debug\src\text\Unicode.o obj\win-cmd\x86_64\clang\clang-debug\src\text\UnicodeData.o obj\win-cmd\x86_64\clang\clang-debug\src\threading\Thread.o obj\win-cmd\x86_64\clang\clang-debug\src\Array.o obj\win-cmd\x86_64\clang\clang-debug\src\Cstring.o obj\win-cmd\x86_64\clang\clang-debug\src\Error.o obj\win-cmd\x86_64\clang\clang-debug\src\IO.o obj\win-cmd\x86_64\clang\clang-debug\src\Mem.o obj\win-cmd\x86_64\clang\clang-debug\src\Slice.o obj\win-cmd\x86_64\clang\clang-debug\src\Std.o obj\win-cmd\x86_64\clang\clang-debug\src\os\WinEx.o
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\containers\Test_BinaryHeap.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_BinaryHeap.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\containers\Test_Hashtable.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_Hashtable.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\containers\Test_List.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_List.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\containers\Test_Vector.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_Vector.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\IO.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\IO.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\Main.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\Main.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\Std.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\Std.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\Test_Array.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Array.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\Test_Cstring.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Cstring.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\Test_Slice.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Slice.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\text\Test_Regex.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_Regex.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\text\Test_String.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_String.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\tests\text\Test_Unicode.c -o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_Unicode.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\BinaryHeap.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\BinaryHeap.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Container.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Container.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Hashtable.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Hashtable.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Iterator.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Iterator.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\List.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\List.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\containers\Vector.c -o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Vector.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Process.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Process.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Signal.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Signal.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\System.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\System.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\os\Timer.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\Timer.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\Regex.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\Regex.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\String.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\String.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\Unicode.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\Unicode.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\text\UnicodeData.c -o obj\win-cmd\x86_64\clang\clang-debug\src\text\UnicodeData.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\threading\Thread.c -o obj\win-cmd\x86_64\clang\clang-debug\src\threading\Thread.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Array.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Array.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Cstring.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Cstring.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Error.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Error.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\IO.c -o obj\win-cmd\x86_64\clang\clang-debug\src\IO.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Mem.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Mem.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Slice.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Slice.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\src\Std.c -o obj\win-cmd\x86_64\clang\clang-debug\src\Std.o 
clang   -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c src\os\WinEx.c -o obj\win-cmd\x86_64\clang\clang-debug\src\os\WinEx.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert\bool.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\bool.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert\null.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\null.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert\result.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\result.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert\size_t.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\size_t.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert\str.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\str.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\assert.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\context.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\context.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\expect.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\expect.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\flut.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\flut.o 
clang  -I.\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -ggdb -O0 -DFL_DEBUG -c .\flut\src\suite.c -o obj\win-cmd\x86_64\clang\clang-debug\flut\src\suite.o 
llvm-lib.exe /NOLOGO /OUT:build\win-cmd\x86_64\clang\clang-debug\libflut.lib  obj\win-cmd\x86_64\clang\clang-debug\src\containers\BinaryHeap.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Container.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Hashtable.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Iterator.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\List.o obj\win-cmd\x86_64\clang\clang-debug\src\containers\Vector.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Process.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Signal.o obj\win-cmd\x86_64\clang\clang-debug\src\os\System.o obj\win-cmd\x86_64\clang\clang-debug\src\os\Timer.o obj\win-cmd\x86_64\clang\clang-debug\src\text\Regex.o obj\win-cmd\x86_64\clang\clang-debug\src\text\String.o obj\win-cmd\x86_64\clang\clang-debug\src\text\Unicode.o obj\win-cmd\x86_64\clang\clang-debug\src\text\UnicodeData.o obj\win-cmd\x86_64\clang\clang-debug\src\threading\Thread.o obj\win-cmd\x86_64\clang\clang-debug\src\Array.o obj\win-cmd\x86_64\clang\clang-debug\src\Cstring.o obj\win-cmd\x86_64\clang\clang-debug\src\Error.o obj\win-cmd\x86_64\clang\clang-debug\src\IO.o obj\win-cmd\x86_64\clang\clang-debug\src\Mem.o obj\win-cmd\x86_64\clang\clang-debug\src\Slice.o obj\win-cmd\x86_64\clang\clang-debug\src\Std.o obj\win-cmd\x86_64\clang\clang-debug\src\os\WinEx.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\bool.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\null.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\result.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\size_t.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert\str.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\assert.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\context.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\expect.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\flut.o obj\win-cmd\x86_64\clang\clang-debug\flut\src\suite.o
link.exe /OUT:build\win-cmd\x86_64\clang\clang-debug\tests.exe /DEFAULTLIB:libcmt.lib /NOLOGO /SUBSYSTEM:CONSOLE /DEBUG:FULL   obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_BinaryHeap.o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_Hashtable.o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_List.o obj\win-cmd\x86_64\clang\clang-debug\tests\containers\Test_Vector.o obj\win-cmd\x86_64\clang\clang-debug\tests\IO.o obj\win-cmd\x86_64\clang\clang-debug\tests\Main.o obj\win-cmd\x86_64\clang\clang-debug\tests\Std.o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Array.o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Cstring.o obj\win-cmd\x86_64\clang\clang-debug\tests\Test_Slice.o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_Regex.o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_String.o obj\win-cmd\x86_64\clang\clang-debug\tests\text\Test_Unicode.o build\win-cmd\x86_64\clang\clang-debug\libflut.lib 
